FROM node:16.19.0-buster-slim

WORKDIR /tmp
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade \
    && apt-get install -y alien libaio1 wget
RUN wget https://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient19.3-basiclite-19.3.0.0.0-1.x86_64.rpm
RUN alien -i --scripts oracle-instantclient*.rpm
RUN rm -f oracle-instantclient19.3*.rpm \
    && apt-get -y autoremove && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /server

COPY ./package.json yarn.lock tsconfig.json* ./
ADD ./compile.sh ./
RUN yarn install --production=false

COPY . .
ADD ./compile.sh ./
CMD [ "yarn", "dev"]
